package com.example.todo.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8C4A60)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9E2)
val onPrimaryContainerLight = Color(0xFF3A071D)
val secondaryLight = Color(0xFF774F83)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFAD7FF)
val onSecondaryContainerLight = Color(0xFF2E0A3B)
val tertiaryLight = Color(0xFF824C76)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F1)
val onTertiaryContainerLight = Color(0xFF35082F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF22191B)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF22191B)
val surfaceVariantLight = Color(0xFFF2DDE1)
val onSurfaceVariantLight = Color(0xFF514347)
val outlineLight = Color(0xFF837377)
val outlineVariantLight = Color(0xFFD5C2C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372E30)
val inverseOnSurfaceLight = Color(0xFFFDEDEF)
val inversePrimaryLight = Color(0xFFFFB1C8)
val surfaceDimLight = Color(0xFFE6D6D9)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F2)
val surfaceContainerLight = Color(0xFFFBEAED)
val surfaceContainerHighLight = Color(0xFFF5E4E7)
val surfaceContainerHighestLight = Color(0xFFEFDFE1)

val primaryDark = Color(0xFFFFB1C8)
val onPrimaryDark = Color(0xFF541D32)
val primaryContainerDark = Color(0xFF703348)
val onPrimaryContainerDark = Color(0xFFFFD9E2)
val secondaryDark = Color(0xFFE6B6F1)
val onSecondaryDark = Color(0xFF462152)
val secondaryContainerDark = Color(0xFF5E386A)
val onSecondaryContainerDark = Color(0xFFFAD7FF)
val tertiaryDark = Color(0xFFF5B2E2)
val onTertiaryDark = Color(0xFF4E1E45)
val tertiaryContainerDark = Color(0xFF68355D)
val onTertiaryContainerDark = Color(0xFFFFD7F1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191113)
val onBackgroundDark = Color(0xFFEFDFE1)
val surfaceDark = Color(0xFF191113)
val onSurfaceDark = Color(0xFFEFDFE1)
val surfaceVariantDark = Color(0xFF514347)
val onSurfaceVariantDark = Color(0xFFD5C2C6)
val outlineDark = Color(0xFF9E8C90)
val outlineVariantDark = Color(0xFF514347)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDFE1)
val inverseOnSurfaceDark = Color(0xFF372E30)
val inversePrimaryDark = Color(0xFF8C4A60)
val surfaceDimDark = Color(0xFF191113)
val surfaceBrightDark = Color(0xFF413739)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF22191B)
val surfaceContainerDark = Color(0xFF261D1F)
val surfaceContainerHighDark = Color(0xFF31282A)
val surfaceContainerHighestDark = Color(0xFF3C3235)







